spring:
  datasource:
    url: jdbc:mysql://192.168.109.6:3306/sps?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    host: 192.168.109.6
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
  cache:
    cache-names: application
    redis:
      time-to-live: 10m

mybatis:
  mapper-locations:
    - classpath*:mapper/*.xml
    - classpath:dao/*.xml
  type-handlers-package: com.remmy.simplepaas.handler

pagehelper:
  page-size-zero: true
  reasonable: true

jwt:
  config:
    key: zaq1xsw2
    ttl: 36000000

redis:
  key:
    image: image

server:
  servlet:
    session:
      timeout: 6h

logstash:
  host: 192.168.109.6:4560

search:
  url: http://search-service

secure:
  ignored:
    urls: #安全路径白名单
      - /css/**
      - /js/**
      - /index.html
      - /img/**
      - /fonts/**
      - /favicon.ico
      - /v2/**
      - /swagger-ui.html
      - /webjars/**
      - /actuator/**
      - /druid/**
      - /doc.html
      - /img.icons/**
      - /swagger-resources/**
      - /swagger/**
      - /v2/api-docs-ext/**
      - /token