spring:
  elasticsearch:
    rest:
      uris: 192.168.109.6:9200
  datasource:
    url: jdbc:mysql://192.168.109.6:3306/sps?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  data:
    elasticsearch:
      repositories:
        enabled: true
mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:mapper/*.xml